// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ClearMapDataHandler(ReducerEventContext ctx, string mapName);
        public event ClearMapDataHandler? OnClearMapData;

        public void ClearMapData(string mapName)
        {
            conn.InternalCallReducer(new Reducer.ClearMapData(mapName), this.SetCallReducerFlags.ClearMapDataFlags);
        }

        public bool InvokeClearMapData(ReducerEventContext ctx, Reducer.ClearMapData args)
        {
            if (OnClearMapData == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnClearMapData(
                ctx,
                args.MapName
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ClearMapData : Reducer, IReducerArgs
        {
            [DataMember(Name = "mapName")]
            public string MapName;

            public ClearMapData(string MapName)
            {
                this.MapName = MapName;
            }

            public ClearMapData()
            {
                this.MapName = "";
            }

            string IReducerArgs.ReducerName => "ClearMapData";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags ClearMapDataFlags;
        public void ClearMapData(CallReducerFlags flags) => ClearMapDataFlags = flags;
    }
}
