// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void MoveAllEntitiesHandler(ReducerEventContext ctx, MoveAllEntitiesTimer timer);
        public event MoveAllEntitiesHandler? OnMoveAllEntities;

        public void MoveAllEntities(MoveAllEntitiesTimer timer)
        {
            conn.InternalCallReducer(new Reducer.MoveAllEntities(timer), this.SetCallReducerFlags.MoveAllEntitiesFlags);
        }

        public bool InvokeMoveAllEntities(ReducerEventContext ctx, Reducer.MoveAllEntities args)
        {
            if (OnMoveAllEntities == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnMoveAllEntities(
                ctx,
                args.Timer
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class MoveAllEntities : Reducer, IReducerArgs
        {
            [DataMember(Name = "timer")]
            public MoveAllEntitiesTimer Timer;

            public MoveAllEntities(MoveAllEntitiesTimer Timer)
            {
                this.Timer = Timer;
            }

            public MoveAllEntities()
            {
                this.Timer = new();
            }

            string IReducerArgs.ReducerName => "MoveAllEntities";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags MoveAllEntitiesFlags;
        public void MoveAllEntities(CallReducerFlags flags) => MoveAllEntitiesFlags = flags;
    }
}
