// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpdatePlayerInputHandler(ReducerEventContext ctx, System.Collections.Generic.List<Input> inputs);
        public event UpdatePlayerInputHandler? OnUpdatePlayerInput;

        public void UpdatePlayerInput(System.Collections.Generic.List<Input> inputs)
        {
            conn.InternalCallReducer(new Reducer.UpdatePlayerInput(inputs), this.SetCallReducerFlags.UpdatePlayerInputFlags);
        }

        public bool InvokeUpdatePlayerInput(ReducerEventContext ctx, Reducer.UpdatePlayerInput args)
        {
            if (OnUpdatePlayerInput == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnUpdatePlayerInput(
                ctx,
                args.Inputs
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpdatePlayerInput : Reducer, IReducerArgs
        {
            [DataMember(Name = "inputs")]
            public System.Collections.Generic.List<Input> Inputs;

            public UpdatePlayerInput(System.Collections.Generic.List<Input> Inputs)
            {
                this.Inputs = Inputs;
            }

            public UpdatePlayerInput()
            {
                this.Inputs = new();
            }

            string IReducerArgs.ReducerName => "UpdatePlayerInput";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags UpdatePlayerInputFlags;
        public void UpdatePlayerInput(CallReducerFlags flags) => UpdatePlayerInputFlags = flags;
    }
}
