// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UploadMapTriangleBatchHandler(ReducerEventContext ctx, string mapName, System.Collections.Generic.List<MapTriangleCell> cells);
        public event UploadMapTriangleBatchHandler? OnUploadMapTriangleBatch;

        public void UploadMapTriangleBatch(string mapName, System.Collections.Generic.List<MapTriangleCell> cells)
        {
            conn.InternalCallReducer(new Reducer.UploadMapTriangleBatch(mapName, cells), this.SetCallReducerFlags.UploadMapTriangleBatchFlags);
        }

        public bool InvokeUploadMapTriangleBatch(ReducerEventContext ctx, Reducer.UploadMapTriangleBatch args)
        {
            if (OnUploadMapTriangleBatch == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnUploadMapTriangleBatch(
                ctx,
                args.MapName,
                args.Cells
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UploadMapTriangleBatch : Reducer, IReducerArgs
        {
            [DataMember(Name = "mapName")]
            public string MapName;
            [DataMember(Name = "cells")]
            public System.Collections.Generic.List<MapTriangleCell> Cells;

            public UploadMapTriangleBatch(
                string MapName,
                System.Collections.Generic.List<MapTriangleCell> Cells
            )
            {
                this.MapName = MapName;
                this.Cells = Cells;
            }

            public UploadMapTriangleBatch()
            {
                this.MapName = "";
                this.Cells = new();
            }

            string IReducerArgs.ReducerName => "UploadMapTriangleBatch";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags UploadMapTriangleBatchFlags;
        public void UploadMapTriangleBatch(CallReducerFlags flags) => UploadMapTriangleBatchFlags = flags;
    }
}
