// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UploadMapConfigHandler(ReducerEventContext ctx, MapConfig config);
        public event UploadMapConfigHandler? OnUploadMapConfig;

        public void UploadMapConfig(MapConfig config)
        {
            conn.InternalCallReducer(new Reducer.UploadMapConfig(config), this.SetCallReducerFlags.UploadMapConfigFlags);
        }

        public bool InvokeUploadMapConfig(ReducerEventContext ctx, Reducer.UploadMapConfig args)
        {
            if (OnUploadMapConfig == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnUploadMapConfig(
                ctx,
                args.Config
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UploadMapConfig : Reducer, IReducerArgs
        {
            [DataMember(Name = "config")]
            public MapConfig Config;

            public UploadMapConfig(MapConfig Config)
            {
                this.Config = Config;
            }

            public UploadMapConfig()
            {
                this.Config = new();
            }

            string IReducerArgs.ReducerName => "UploadMapConfig";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags UploadMapConfigFlags;
        public void UploadMapConfig(CallReducerFlags flags) => UploadMapConfigFlags = flags;
    }
}
