// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UploadMapHeightmapBatchHandler(ReducerEventContext ctx, string mapName, System.Collections.Generic.List<MapHeightmapPatch> patches);
        public event UploadMapHeightmapBatchHandler? OnUploadMapHeightmapBatch;

        public void UploadMapHeightmapBatch(string mapName, System.Collections.Generic.List<MapHeightmapPatch> patches)
        {
            conn.InternalCallReducer(new Reducer.UploadMapHeightmapBatch(mapName, patches), this.SetCallReducerFlags.UploadMapHeightmapBatchFlags);
        }

        public bool InvokeUploadMapHeightmapBatch(ReducerEventContext ctx, Reducer.UploadMapHeightmapBatch args)
        {
            if (OnUploadMapHeightmapBatch == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnUploadMapHeightmapBatch(
                ctx,
                args.MapName,
                args.Patches
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UploadMapHeightmapBatch : Reducer, IReducerArgs
        {
            [DataMember(Name = "mapName")]
            public string MapName;
            [DataMember(Name = "patches")]
            public System.Collections.Generic.List<MapHeightmapPatch> Patches;

            public UploadMapHeightmapBatch(
                string MapName,
                System.Collections.Generic.List<MapHeightmapPatch> Patches
            )
            {
                this.MapName = MapName;
                this.Patches = Patches;
            }

            public UploadMapHeightmapBatch()
            {
                this.MapName = "";
                this.Patches = new();
            }

            string IReducerArgs.ReducerName => "UploadMapHeightmapBatch";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags UploadMapHeightmapBatchFlags;
        public void UploadMapHeightmapBatch(CallReducerFlags flags) => UploadMapHeightmapBatchFlags = flags;
    }
}
