// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Entity
    {
        [DataMember(Name = "EntityId")]
        public uint EntityId;
        [DataMember(Name = "Speed")]
        public float Speed;
        [DataMember(Name = "Position")]
        public DbVector3 Position;
        [DataMember(Name = "Direction")]
        public DbVector2 Direction;
        [DataMember(Name = "Rotation")]
        public float Rotation;
        [DataMember(Name = "SequenceId")]
        public ulong SequenceId;
        [DataMember(Name = "Allegiance")]
        public Faction Allegiance;
        [DataMember(Name = "TargetEntityId")]
        public uint TargetEntityId;
        [DataMember(Name = "VerticalVelocity")]
        public float VerticalVelocity;
        [DataMember(Name = "IsGrounded")]
        public bool IsGrounded;

        public Entity(
            uint EntityId,
            float Speed,
            DbVector3 Position,
            DbVector2 Direction,
            float Rotation,
            ulong SequenceId,
            Faction Allegiance,
            uint TargetEntityId,
            float VerticalVelocity,
            bool IsGrounded
        )
        {
            this.EntityId = EntityId;
            this.Speed = Speed;
            this.Position = Position;
            this.Direction = Direction;
            this.Rotation = Rotation;
            this.SequenceId = SequenceId;
            this.Allegiance = Allegiance;
            this.TargetEntityId = TargetEntityId;
            this.VerticalVelocity = VerticalVelocity;
            this.IsGrounded = IsGrounded;
        }

        public Entity()
        {
            this.Position = new();
            this.Direction = new();
        }
    }
}
