// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class EntityUpdate
    {
        [DataMember(Name = "Id")]
        public uint Id;
        [DataMember(Name = "LastTickedAt")]
        public SpacetimeDB.Timestamp LastTickedAt;
        [DataMember(Name = "DeltaTime")]
        public float DeltaTime;

        public EntityUpdate(
            uint Id,
            SpacetimeDB.Timestamp LastTickedAt,
            float DeltaTime
        )
        {
            this.Id = Id;
            this.LastTickedAt = LastTickedAt;
            this.DeltaTime = DeltaTime;
        }

        public EntityUpdate()
        {
        }
    }
}
