// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Input
    {
        [DataMember(Name = "SequenceId")]
        public ulong SequenceId;
        [DataMember(Name = "Direction")]
        public DbVector2 Direction;
        [DataMember(Name = "TargetEntityId")]
        public uint TargetEntityId;

        public Input(
            ulong SequenceId,
            DbVector2 Direction,
            uint TargetEntityId
        )
        {
            this.SequenceId = SequenceId;
            this.Direction = Direction;
            this.TargetEntityId = TargetEntityId;
        }

        public Input()
        {
            this.Direction = new();
        }
    }
}
