// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Line
    {
        [DataMember(Name = "Id")]
        public uint Id;
        [DataMember(Name = "Start")]
        public DbVector2 Start;
        [DataMember(Name = "End")]
        public DbVector2 End;

        public Line(
            uint Id,
            DbVector2 Start,
            DbVector2 End
        )
        {
            this.Id = Id;
            this.Start = Start;
            this.End = End;
        }

        public Line()
        {
            this.Start = new();
            this.End = new();
        }
    }
}
