// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class MapConfig
    {
        [DataMember(Name = "MapName")]
        public string MapName;
        [DataMember(Name = "SpawnX")]
        public float SpawnX;
        [DataMember(Name = "SpawnY")]
        public float SpawnY;
        [DataMember(Name = "SpawnZ")]
        public float SpawnZ;
        [DataMember(Name = "HeightmapOriginX")]
        public float HeightmapOriginX;
        [DataMember(Name = "HeightmapOriginZ")]
        public float HeightmapOriginZ;
        [DataMember(Name = "HeightmapSizeX")]
        public float HeightmapSizeX;
        [DataMember(Name = "HeightmapSizeZ")]
        public float HeightmapSizeZ;
        [DataMember(Name = "HeightmapResolution")]
        public int HeightmapResolution;
        [DataMember(Name = "HeightmapPatchSize")]
        public int HeightmapPatchSize;
        [DataMember(Name = "TriangleCellSize")]
        public float TriangleCellSize;

        public MapConfig(
            string MapName,
            float SpawnX,
            float SpawnY,
            float SpawnZ,
            float HeightmapOriginX,
            float HeightmapOriginZ,
            float HeightmapSizeX,
            float HeightmapSizeZ,
            int HeightmapResolution,
            int HeightmapPatchSize,
            float TriangleCellSize
        )
        {
            this.MapName = MapName;
            this.SpawnX = SpawnX;
            this.SpawnY = SpawnY;
            this.SpawnZ = SpawnZ;
            this.HeightmapOriginX = HeightmapOriginX;
            this.HeightmapOriginZ = HeightmapOriginZ;
            this.HeightmapSizeX = HeightmapSizeX;
            this.HeightmapSizeZ = HeightmapSizeZ;
            this.HeightmapResolution = HeightmapResolution;
            this.HeightmapPatchSize = HeightmapPatchSize;
            this.TriangleCellSize = TriangleCellSize;
        }

        public MapConfig()
        {
            this.MapName = "";
        }
    }
}
