// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class MapHeightmapPatch
    {
        [DataMember(Name = "Id")]
        public ulong Id;
        [DataMember(Name = "MapName")]
        public string MapName;
        [DataMember(Name = "PatchX")]
        public int PatchX;
        [DataMember(Name = "PatchZ")]
        public int PatchZ;
        [DataMember(Name = "Heights")]
        public System.Collections.Generic.List<float> Heights;

        public MapHeightmapPatch(
            ulong Id,
            string MapName,
            int PatchX,
            int PatchZ,
            System.Collections.Generic.List<float> Heights
        )
        {
            this.Id = Id;
            this.MapName = MapName;
            this.PatchX = PatchX;
            this.PatchZ = PatchZ;
            this.Heights = Heights;
        }

        public MapHeightmapPatch()
        {
            this.MapName = "";
            this.Heights = new();
        }
    }
}
