// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class MapTriangleCell
    {
        [DataMember(Name = "Id")]
        public ulong Id;
        [DataMember(Name = "MapName")]
        public string MapName;
        [DataMember(Name = "CellX")]
        public int CellX;
        [DataMember(Name = "CellZ")]
        public int CellZ;
        [DataMember(Name = "V0X")]
        public float V0X;
        [DataMember(Name = "V0Y")]
        public float V0Y;
        [DataMember(Name = "V0Z")]
        public float V0Z;
        [DataMember(Name = "V1X")]
        public float V1X;
        [DataMember(Name = "V1Y")]
        public float V1Y;
        [DataMember(Name = "V1Z")]
        public float V1Z;
        [DataMember(Name = "V2X")]
        public float V2X;
        [DataMember(Name = "V2Y")]
        public float V2Y;
        [DataMember(Name = "V2Z")]
        public float V2Z;

        public MapTriangleCell(
            ulong Id,
            string MapName,
            int CellX,
            int CellZ,
            float V0X,
            float V0Y,
            float V0Z,
            float V1X,
            float V1Y,
            float V1Z,
            float V2X,
            float V2Y,
            float V2Z
        )
        {
            this.Id = Id;
            this.MapName = MapName;
            this.CellX = CellX;
            this.CellZ = CellZ;
            this.V0X = V0X;
            this.V0Y = V0Y;
            this.V0Z = V0Z;
            this.V1X = V1X;
            this.V1Y = V1Y;
            this.V1Z = V1Z;
            this.V2X = V2X;
            this.V2Y = V2Y;
            this.V2Z = V2Z;
        }

        public MapTriangleCell()
        {
            this.MapName = "";
        }
    }
}
