// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class MapTile
    {
        [DataMember(Name = "Id")]
        public uint Id;
        [DataMember(Name = "Position")]
        public DbVector2 Position;
        [DataMember(Name = "Width")]
        public float Width;
        [DataMember(Name = "Height")]
        public float Height;

        public MapTile(
            uint Id,
            DbVector2 Position,
            float Width,
            float Height
        )
        {
            this.Id = Id;
            this.Position = Position;
            this.Width = Width;
            this.Height = Height;
        }

        public MapTile()
        {
            this.Position = new();
        }
    }
}
