// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PlayerInput
    {
        [DataMember(Name = "Id")]
        public ulong Id;
        [DataMember(Name = "EntityId")]
        public uint EntityId;
        [DataMember(Name = "SequenceId")]
        public ulong SequenceId;
        [DataMember(Name = "TargetEntityId")]
        public uint TargetEntityId;
        [DataMember(Name = "Direction")]
        public DbVector2 Direction;

        public PlayerInput(
            ulong Id,
            uint EntityId,
            ulong SequenceId,
            uint TargetEntityId,
            DbVector2 Direction
        )
        {
            this.Id = Id;
            this.EntityId = EntityId;
            this.SequenceId = SequenceId;
            this.TargetEntityId = TargetEntityId;
            this.Direction = Direction;
        }

        public PlayerInput()
        {
            this.Direction = new();
        }
    }
}
