// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PlayerInput
    {
        [DataMember(Name = "PlayerId")]
        public uint PlayerId;
        [DataMember(Name = "Direction")]
        public DbVector2 Direction;
        [DataMember(Name = "SequenceId")]
        public ulong SequenceId;

        public PlayerInput(
            uint PlayerId,
            DbVector2 Direction,
            ulong SequenceId
        )
        {
            this.PlayerId = PlayerId;
            this.Direction = Direction;
            this.SequenceId = SequenceId;
        }

        public PlayerInput()
        {
            this.Direction = new();
        }
    }
}
