// Auto-generated by MapExporter. Do not edit.
namespace SharedPhysics
{
    public static partial class MapData
    {
        public static MapDefinition GetMap(string name) => name switch
        {
            "Default" => Default,
            "Forest" => Forest,
            _ => throw new System.ArgumentException($"Unknown map: {name}")
        };

        private static Line[] BuildLines(float[] data)
        {
            var result = new Line[data.Length / 4];
            for (int i = 0; i < result.Length; i++)
            {
                int j = i * 4;
                result[i] = new Line(new Vector2(data[j], data[j + 1]), new Vector2(data[j + 2], data[j + 3]));
            }
            return result;
        }

        private static Triangle[] BuildTriangles(float[] data)
        {
            var result = new Triangle[data.Length / 9];
            for (int i = 0; i < result.Length; i++)
            {
                int j = i * 9;
                result[i] = new Triangle(
                    new Vector3(data[j], data[j + 1], data[j + 2]),
                    new Vector3(data[j + 3], data[j + 4], data[j + 5]),
                    new Vector3(data[j + 6], data[j + 7], data[j + 8]));
            }
            return result;
        }
    }
}
