// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class LineHandle : RemoteTableHandle<EventContext, Line>
        {
            protected override string RemoteTableName => "Line";

            public sealed class IdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(Line row) => row.Id;

                public IdUniqueIndex(LineHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal LineHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }
        }

        public readonly LineHandle Line;
    }
}
