// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class MapConfigHandle : RemoteTableHandle<EventContext, MapConfig>
        {
            protected override string RemoteTableName => "MapConfig";

            public sealed class MapNameUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(MapConfig row) => row.MapName;

                public MapNameUniqueIndex(MapConfigHandle table) : base(table) { }
            }

            public readonly MapNameUniqueIndex MapName;

            internal MapConfigHandle(DbConnection conn) : base(conn)
            {
                MapName = new(this);
            }

            protected override object GetPrimaryKey(MapConfig row) => row.MapName;
        }

        public readonly MapConfigHandle MapConfig;
    }
}
