// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class MapHeightmapPatchHandle : RemoteTableHandle<EventContext, MapHeightmapPatch>
        {
            protected override string RemoteTableName => "MapHeightmapPatch";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(MapHeightmapPatch row) => row.Id;

                public IdUniqueIndex(MapHeightmapPatchHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class MapNamePatchXPatchZIndex : BTreeIndexBase<(string MapName, int PatchX, int PatchZ)>
            {
                protected override (string MapName, int PatchX, int PatchZ) GetKey(MapHeightmapPatch row) => (row.MapName, row.PatchX, row.PatchZ);

                public MapNamePatchXPatchZIndex(MapHeightmapPatchHandle table) : base(table) { }
            }

            public readonly MapNamePatchXPatchZIndex MapNamePatchXPatchZ;

            internal MapHeightmapPatchHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                MapNamePatchXPatchZ = new(this);
            }

            protected override object GetPrimaryKey(MapHeightmapPatch row) => row.Id;
        }

        public readonly MapHeightmapPatchHandle MapHeightmapPatch;
    }
}
