// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class MapTriangleCellHandle : RemoteTableHandle<EventContext, MapTriangleCell>
        {
            protected override string RemoteTableName => "MapTriangleCell";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(MapTriangleCell row) => row.Id;

                public IdUniqueIndex(MapTriangleCellHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class MapNameCellXCellZIndex : BTreeIndexBase<(string MapName, int CellX, int CellZ)>
            {
                protected override (string MapName, int CellX, int CellZ) GetKey(MapTriangleCell row) => (row.MapName, row.CellX, row.CellZ);

                public MapNameCellXCellZIndex(MapTriangleCellHandle table) : base(table) { }
            }

            public readonly MapNameCellXCellZIndex MapNameCellXCellZ;

            internal MapTriangleCellHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                MapNameCellXCellZ = new(this);
            }

            protected override object GetPrimaryKey(MapTriangleCell row) => row.Id;
        }

        public readonly MapTriangleCellHandle MapTriangleCell;
    }
}
