// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class MoveAllEntitiesTimerHandle : RemoteTableHandle<EventContext, MoveAllEntitiesTimer>
        {
            protected override string RemoteTableName => "moveAllEntitiesTimer";

            public sealed class ScheduledIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(MoveAllEntitiesTimer row) => row.ScheduledId;

                public ScheduledIdUniqueIndex(MoveAllEntitiesTimerHandle table) : base(table) { }
            }

            public readonly ScheduledIdUniqueIndex ScheduledId;

            internal MoveAllEntitiesTimerHandle(DbConnection conn) : base(conn)
            {
                ScheduledId = new(this);
            }

            protected override object GetPrimaryKey(MoveAllEntitiesTimer row) => row.ScheduledId;
        }

        public readonly MoveAllEntitiesTimerHandle MoveAllEntitiesTimer;
    }
}
