// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PlayerInputHandle : RemoteTableHandle<EventContext, PlayerInput>
        {
            protected override string RemoteTableName => "PlayerInput";

            public sealed class PlayerIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(PlayerInput row) => row.PlayerId;

                public PlayerIdUniqueIndex(PlayerInputHandle table) : base(table) { }
            }

            public readonly PlayerIdUniqueIndex PlayerId;

            internal PlayerInputHandle(DbConnection conn) : base(conn)
            {
                PlayerId = new(this);
            }

            protected override object GetPrimaryKey(PlayerInput row) => row.PlayerId;
        }

        public readonly PlayerInputHandle PlayerInput;
    }
}
