// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PlayerInputHandle : RemoteTableHandle<EventContext, PlayerInput>
        {
            protected override string RemoteTableName => "PlayerInput";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(PlayerInput row) => row.Id;

                public IdUniqueIndex(PlayerInputHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class PlayerIdSequenceIdIndex : BTreeIndexBase<(uint PlayerId, ulong SequenceId)>
            {
                protected override (uint PlayerId, ulong SequenceId) GetKey(PlayerInput row) => (row.PlayerId, row.SequenceId);

                public PlayerIdSequenceIdIndex(PlayerInputHandle table) : base(table) { }
            }

            public readonly PlayerIdSequenceIdIndex PlayerIdSequenceId;

            public sealed class PlayerIdIndex : BTreeIndexBase<uint>
            {
                protected override uint GetKey(PlayerInput row) => row.PlayerId;

                public PlayerIdIndex(PlayerInputHandle table) : base(table) { }
            }

            public readonly PlayerIdIndex PlayerId;

            public sealed class SequenceIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(PlayerInput row) => row.SequenceId;

                public SequenceIdIndex(PlayerInputHandle table) : base(table) { }
            }

            public readonly SequenceIdIndex SequenceId;

            internal PlayerInputHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                PlayerIdSequenceId = new(this);
                PlayerId = new(this);
                SequenceId = new(this);
            }

            protected override object GetPrimaryKey(PlayerInput row) => row.Id;
        }

        public readonly PlayerInputHandle PlayerInput;
    }
}
